# Generated by Django 4.2.1 on 2023-06-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Events", "0002_events_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="event_links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
