# Generated by Django 4.2.1 on 2023-06-13 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Events", "0003_events_event_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
