version: "3"
services:
  redis:
    image: redis
    container_name: sema-redis
    ports:
      - "6379:6379"
    restart: on-failure
    command: redis-server --slaveof no one
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sema-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app
    command: >
      sh -c "daphne -b 0.0.0.0 -p 8000 _project.asgi:application"
    depends_on:
      - redis
    restart: always
