# Generated by Django 4.2.1 on 2023-08-10 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("total_comments", models.IntegerField(default=0)),
                ("total_likes", models.IntegerField(default=0)),
                ("total_shares", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Forums",
                "ordering": ("-created_on",),
            },
        ),
        migrations.RemoveField(
            model_name="sharedfile",
            name="upload_date",
        ),
        migrations.AlterField(
            model_name="sharedfile",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="VirtualMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_url", models.URLField()),
                ("scheduled_start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        related_name="virtual_meeting_attendees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_meeting_room",
                        to="Forum.forum",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_organizer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Virtual_Meetings",
                "ordering": ("-created_on",),
            },
        ),
        migrations.CreateModel(
            name="ForumFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("file_url", models.CharField(blank=True, max_length=255, null=True)),
                ("file_key", models.CharField(blank=True, max_length=255, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "forum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_file",
                        to="Forum.forum",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_file_uploader",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Forum_Files",
                "ordering": ("-created_on",),
            },
        ),
        migrations.CreateModel(
            name="ForumComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "commentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_commentor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_comment",
                        to="Forum.forum",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_parent_comment",
                        to="Forum.forumcomment",
                    ),
                ),
            ],
            options={
                "db_table": "Forum_Comments",
                "ordering": ("-created_on",),
            },
        ),
    ]
