# Generated by Django 4.2.1 on 2023-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0002_forum_remove_sharedfile_upload_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="tags",
            field=models.JSONField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forumfile",
            name="file_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sharedfile",
            name="file_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="forumfile",
            name="file_key",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="forumfile",
            name="file_url",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sharedfile",
            name="file_key",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sharedfile",
            name="file_url",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
