# Generated by Django 4.2.1 on 2023-08-10 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Forum", "0004_chatroom_forum_alter_chatroom_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="virtualmeeting",
            old_name="end_time",
            new_name="scheduled_end_time",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="total_members",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="forum",
            name="forum_likers",
            field=models.ManyToManyField(
                related_name="forum_likers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="virtualmeeting",
            name="meeting_agenda",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="virtualmeeting",
            name="total_attendees",
            field=models.IntegerField(default=0),
        ),
    ]
