# Generated by Django 4.2.1 on 2023-08-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0005_rename_end_time_virtualmeeting_scheduled_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="header_image",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="forum",
            name="header_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
