# Generated by Django 4.2.1 on 2023-08-22 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0007_forum_forum_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forum",
            old_name="forum_member",
            new_name="forum_members",
        ),
    ]
