# Generated by Django 4.2.1 on 2023-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0008_rename_forum_member_forum_forum_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="total_members",
            field=models.IntegerField(default=0),
        ),
    ]
