# Generated by Django 4.2.1 on 2023-08-22 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0009_forum_total_members"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ForumComment",
        ),
    ]
