# Generated by Django 4.2.1 on 2023-08-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0011_remove_forum_total_comments_chatroom_total_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="forum",
            name="is_declined",
            field=models.BooleanField(default=False),
        ),
    ]
