# Generated by Django 4.2.1 on 2023-08-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0013_forum_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
