# Generated by Django 4.2.1 on 2023-08-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0014_forum_approved_on_forum_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="decline_comment",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
