# Generated by Django 4.2.1 on 2023-08-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0015_forum_decline_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="approved_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
