# Generated by Django 4.2.1 on 2023-08-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0017_forumrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="forumrequest",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="forumrequest",
            name="is_declined",
            field=models.BooleanField(default=False),
        ),
    ]
