# Generated by Django 4.2.1 on 2023-09-03 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Forum", "0018_forumrequest_is_approved_forumrequest_is_declined"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoomMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("is_media", models.BooleanField(default=False)),
                ("media_files", models.JSONField(blank=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "chat_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_room_messages",
                        to="Forum.chatroom",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Chat_Room_Messages",
                "ordering": ("-created_on",),
            },
        ),
    ]
