# Generated by Django 4.2.1 on 2023-09-13 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0021_forumfile_file_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtualmeeting",
            name="attendees",
        ),
    ]
