# Generated by Django 4.2.1 on 2023-09-13 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0002_user_profile_image_key"),
        ("Forum", "0023_virtualmeetingattendees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="virtualmeetingattendees",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_country",
                to="Auth.country",
            ),
        ),
    ]
