# Generated by Django 4.2.1 on 2023-09-13 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0024_alter_virtualmeetingattendees_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="virtualmeetingattendees",
            name="city",
        ),
    ]
