# Generated by Django 4.2.1 on 2023-09-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0027_forumpoll_is_ended"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroommessages",
            name="file_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
