# Generated by Django 4.2.1 on 2023-09-21 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Forum", "0028_chatroommessages_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="total_comments",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ForumDiscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("is_forum_admin", models.BooleanField(default=False)),
                ("total_likes", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "commentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_commentor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_discussion",
                        to="Forum.forum",
                    ),
                ),
                (
                    "forum_comment_likers",
                    models.ManyToManyField(
                        related_name="forum_comment_likers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "Forum_Discussion",
                "ordering": ("created_on",),
            },
        ),
    ]
