# Generated by Django 4.2.1 on 2023-09-26 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0029_forum_total_comments_forumdiscussion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedfile",
            name="description",
        ),
    ]
