# Generated by Django 4.2.1 on 2023-07-07 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("censored_content", models.TextField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("links", models.JSONField(blank=True, null=True)),
                (
                    "cover_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image_key", models.CharField(blank=True, max_length=255, null=True)),
                ("reference", models.JSONField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("is_abusive", models.BooleanField(default=False)),
                ("is_consented", models.BooleanField(default=False)),
                ("total_likes", models.IntegerField(blank=True, default=0, null=True)),
                ("total_shares", models.IntegerField(blank=True, default=0, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_and_published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "likers",
                    models.ManyToManyField(
                        related_name="blog_likers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "Blog_Posts",
                "ordering": ("-created_on",),
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog",
                        to="Blog.blogpost",
                    ),
                ),
                (
                    "commentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Blog_Comments",
                "ordering": ("-created_on",),
            },
        ),
    ]
