# Generated by Django 4.2.1 on 2023-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_blogpost_blog_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
