# Generated by Django 4.2.1 on 2023-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0003_blogpost_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
