# Generated by Django 4.2.1 on 2023-06-11 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0005_alter_blogpost_options_blogpost_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcomment",
            options={"ordering": ("-created_on",)},
        ),
    ]
