# Generated by Django 4.2.1 on 2023-06-11 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0007_blogpost_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="blog_image_url",
        ),
    ]
