# Generated by Django 4.2.1 on 2023-06-11 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0008_remove_blogpost_blog_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="bloge_image_location",
            new_name="blog_image_location",
        ),
    ]
