# Generated by Django 4.2.1 on 2023-06-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0009_rename_bloge_image_location_blogpost_blog_image_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="blog_links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
