# Generated by Django 4.2.1 on 2023-06-14 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0012_blogpost_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="blog_image_location",
        ),
    ]
