# Generated by Django 4.2.1 on 2023-06-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0013_remove_blogpost_blog_image_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="total_likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
