# Generated by Django 4.2.1 on 2023-06-14 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Blog", "0014_blogpost_total_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="likers",
            field=models.ManyToManyField(
                related_name="blog_likers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
