# Generated by Django 4.2.1 on 2023-06-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0015_blogpost_likers"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="total_shares",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
