# Generated by Django 4.2.1 on 2023-06-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0017_blogpost_censored_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_abusive",
            field=models.BooleanField(default=False),
        ),
    ]
