# Generated by Django 4.2.1 on 2023-06-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0018_blogpost_is_abusive"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="blog_links",
            new_name="reference",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_consented",
            field=models.BooleanField(default=False),
        ),
    ]
