# Generated by Django 4.2.1 on 2023-06-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0020_blogpost_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
