# Generated by Django 4.2.1 on 2023-06-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0022_remove_blogpost_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
