# Generated by Django 4.2.1 on 2023-06-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0023_blogpost_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
