# Generated by Django 4.2.1 on 2023-06-17 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pollchoices",
            options={"ordering": ("created_on",)},
        ),
    ]
