# Generated by Django 4.2.1 on 2023-07-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="approved_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
