# Generated by Django 4.2.1 on 2023-07-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0002_poll_approved_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="poll",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
