# Generated by Django 4.2.1 on 2023-06-17 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Polls", "0002_alter_pollchoices_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="voters",
            field=models.ManyToManyField(
                related_name="poll_voters", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
