# Generated by Django 4.2.1 on 2023-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0003_alter_poll_end_date_alter_poll_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="description",
            new_name="comments",
        ),
        migrations.AddField(
            model_name="poll",
            name="file_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="file_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
