# Generated by Django 4.2.1 on 2023-06-18 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0004_pollchoices_voter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pollchoices",
            name="voter",
        ),
    ]
