# Generated by Django 4.2.1 on 2023-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0004_rename_description_poll_comments_poll_file_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="comments",
        ),
        migrations.AddField(
            model_name="pollvote",
            name="comments",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
