# Generated by Django 4.2.1 on 2023-06-18 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0005_remove_pollchoices_voter"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollVotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("votes", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
                (
                    "poll_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to="Polls.poll",
                    ),
                ),
            ],
            options={
                "db_table": "Poll_Votes",
                "ordering": ("created_on",),
            },
        ),
    ]
