# Generated by Django 4.2.1 on 2023-06-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0007_remove_pollchoices_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollvotes",
            name="poll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_for_choice",
                to="Polls.poll",
            ),
        ),
        migrations.AlterField(
            model_name="pollvotes",
            name="poll_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_choice",
                to="Polls.pollchoices",
            ),
        ),
    ]
