# Generated by Django 4.2.1 on 2023-07-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0007_rename_snaphot_location_poll_snapshot_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="is_declined",
            field=models.BooleanField(default=False),
        ),
    ]
