# Generated by Django 4.2.1 on 2023-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0008_pollvotes_poll_alter_pollvotes_poll_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="poll",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
