# Generated by Django 4.2.1 on 2023-06-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0009_poll_end_date_poll_is_approved_poll_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="is_ended",
            field=models.BooleanField(default=False),
        ),
    ]
