# Generated by Django 4.2.1 on 2023-07-03 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Polls", "0011_pollvotes_choice_voters"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Poll_Votes",
                "ordering": ("created_on",),
            },
        ),
        migrations.RemoveField(
            model_name="poll",
            name="voters",
        ),
        migrations.AddField(
            model_name="pollchoices",
            name="votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pollvote",
            name="poll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_for_choice",
                to="Polls.poll",
            ),
        ),
        migrations.AddField(
            model_name="pollvote",
            name="poll_choice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_choice",
                to="Polls.pollchoices",
            ),
        ),
        migrations.AddField(
            model_name="pollvote",
            name="voter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choice_voter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
