# Generated by Django 4.2.1 on 2023-07-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Polls", "0012_pollvote_remove_poll_voters_pollchoices_votes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
