# Generated by Django 4.2.1 on 2023-07-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
