# Generated by Django 4.2.1 on 2023-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0002_user_profile_image_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_login_field",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
