# Generated by Django 4.2.1 on 2023-06-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0004_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
