# Generated by Django 4.2.1 on 2023-06-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0005_remove_user_phone_number_user_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
