# Generated by Django 4.2.1 on 2023-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0006_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_reset_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
