# Generated by Django 4.2.1 on 2023-06-05 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0007_alter_user_password_reset_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrole",
            old_name="Updated_on",
            new_name="updated_on",
        ),
    ]
