# Generated by Django 4.2.1 on 2023-06-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0009_modules_permission"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Modules",
            new_name="Module",
        ),
        migrations.AddField(
            model_name="permission",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module",
                to="Auth.module",
            ),
        ),
        migrations.AlterModelTable(
            name="permission",
            table="Permission_Manager",
        ),
    ]
