# Generated by Django 4.2.1 on 2023-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0012_user_updated_on"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("abbreviation", models.CharField(blank=True, max_length=255)),
                ("calling_code", models.CharField(blank=True, max_length=255)),
                ("flag", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "Countries",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
    ]
