# Generated by Django 4.2.1 on 2023-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0014_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
