# Generated by Django 4.2.1 on 2023-06-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0015_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
