# Generated by Django 4.2.1 on 2023-06-14 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Auth", "0018_user_links"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserDocuments",
        ),
    ]
