# Generated by Django 4.2.1 on 2023-07-07 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "User_Documents",
                "ordering": ("created_on",),
            },
        ),
        migrations.CreateModel(
            name="EventDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_document",
                        to="Events.events",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_document_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Event_Documents",
                "ordering": ("created_on",),
            },
        ),
        migrations.CreateModel(
            name="BlogDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "document_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_document",
                        to="Blog.blogpost",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_document_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Blog_Documents",
                "ordering": ("created_on",),
            },
        ),
    ]
