# Generated by Django 4.2.1 on 2023-06-14 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0012_blogpost_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Events", "0004_events_approved_by_events_is_approved"),
        ("Utilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdocuments",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EventDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "events",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_document",
                        to="Events.events",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_document_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Event_Documents",
                "ordering": ("created_on",),
            },
        ),
        migrations.CreateModel(
            name="BlogDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "blog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_document",
                        to="Blog.blogpost",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_document_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Blog_Documents",
                "ordering": ("created_on",),
            },
        ),
    ]
