# Generated by Django 4.2.1 on 2023-06-14 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Utilities", "0002_alter_userdocuments_owner_eventdocuments_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventdocuments",
            old_name="events",
            new_name="event",
        ),
    ]
