# Generated by Django 4.2.1 on 2023-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Utilities", "0003_rename_events_eventdocuments_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdocuments",
            name="document_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventdocuments",
            name="document_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userdocuments",
            name="document_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
